#!/bin/sh

if [ "$1" = '' ] || [ "$2" = '' ]; then
	exit
fi

RESULT=$(xinput | grep "$2")
if [ "$RESULT" != '' ]; then
	xinput disable "$1"
else
	if [ "$(xinput list "$1" | grep disabled)" != '' ]; then
		xinput enable "$1"
	fi
fi
